[package]
name = "site"
edition = "2018"
readme = "../README.md"
repository = "https://github.com/rikhuijzer/printpilot"
publish = false

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.80"
features = ["Window", "Document", "File", "FileList", "HtmlElement", "HtmlInputElement", "Text"]
