[workspace]
resolver = "2"
members = [
    "core",
    "site",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
repository = "https://github.com/rikhuijzer/printpilot"
