[package]
name = "core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
publish = false

[dependencies]
ciborium = "0.2"
serde_json = "1.0"
serde = "1"
