name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: 'stable'
          target: 'wasm32-unknown-unknown'
          override: 'false'
          components: 'rustfmt, clippy'
        
      - run: cargo build

      - if: github.ref != 'refs/heads/main'
        run: cargo fmt --all -- --check

      - if: github.ref != 'refs/heads/main'
        run: cargo clippy -- -Dwarnings

      - uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - run: trunk build

      - uses: cloudflare/wrangler-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy public --project-name=printpilot --branch=main
